---ayesian AB Testing"
output: html_notebook
---

How to evaluate the effect in Convertion of a Discount Experiment

Libraries

```{r}
library(bayesAB)
```

Original Data from Discount Experiment

```{r}
Tot.base<-14449 # number of base cases
Conv.base<-208 # number of base converions
Tot.desc<-3479 # number of discount cases
Conv.desc<-69 # number of conversions with discount
# Convet to vectors
Vec.base <- c(rep(1,Conv.base),rep(0,Tot.base-Conv.base))
Vec.desc <- c(rep(1,Conv.desc),rep(0,Tot.desc-Conv.desc))
# Conversion Rate No Discount
Conv.base/Tot.base # NO Discount
# Conversion Rate with Discount
Conv.desc/Tot.desc # WITH Discount
```

########################
Frequentist Approach
Is the CR increase statistically significant ?
########################

Fishers exact test for odds ratio equal to 1

```{r}
matriz<-matrix(c(Conv.desc,Conv.base,Tot.desc-Conv.desc,Tot.base-Conv.base), 2,2)
rownames(matriz)<-c("Desc", "Base")
colnames(matriz)<-c("Yes", "No")
matriz
fisher.test(matriz)
```



Alternative test for difference of proportions

```{r}
TEST<-prop.test(c (Conv.desc, Conv.base), c (Tot.desc, Tot.base),alternative="greater")
TEST
```

######################
Bayesian Approach
######################

```{r}
# Non Informative prior (uniform distribution)
AB1 <- bayesTest (Vec.desc, Vec.base,
                 priors = c ('alpha' = 1, 'beta' = 1),
                 distribution = 'bernoulli')
# Low conversion rate prior
#AB1 <- bayesTest (Vec.desc, Vec.base,
#                 priors = c ('alpha' = 1, 'beta' = 5),
#                 distribution = 'bernoulli')
```

Results

```{r}
AB1
```

Summary

```{r}
summary(AB1)
```


Descriptive Plots

```{r}
p <- plot(AB1)
p$priors
p$posterior
p$samples
```

